name: Check all links in the repository
on: [push]
 
jobs:
  run:
    name: Link Check All
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-http-header-size=65536'
    steps:
      - uses: actions/checkout@v3
      - name: Run Link Check
        id: check
        run: npx repo-link-check -c ./config/link-check/config.yml
